### ISSUE TITLE
Json serializer should not include bean info in resulted json

### ISSUE THREAD

**Issue by huybanh** [huybanh/b3#24]

**Comment by namhnt** [comment]
done 
Test output:

{"class":"com.betbrain.sepc.connector.sportsmodel.Event","currentPartId":100,"deleteTimeOffset":0,"displayName":"Event","endTime":null,"hasLiveStatus":false,"id":0,"isComplete":false,"name":null,"note":null,"parentId":null,"parentPartId":null,"popularity":null,"promotionId":null,"rootPartId":0,"sportId":0,"startTime":1234,"statusId":0,"templateId":null,"typeId":0,"url":null,"venueId":null}
